apiVersion: v1
kind: PersistentVolume
metadata:
  name: flask-api-log-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data/flask-api-log


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flask-api-log-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
